jobs:
  draft-release:
    environment: Production
    name: Draft release
    outputs:
      release-id: ${{ steps.step-create-draft.outputs.release-id }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    - continue-on-error: true
      name: Set Maven dependencies cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: step-create-draft
      name: Create release draft
      run: ./.github/workflows/scripts/create-draft-release.sh
  publish-release:
    environment: Production
    name: Publish release
    needs:
    - draft-release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_ID: ${{ needs.draft-release.outputs.release-id }}
      name: Approve release
      run: '. ./.github/workflows/scripts/github-functions.sh

        echo $(__approveAsset)

        '
on:
  repository_dispatch:
    types: trigger-ga___release.yml
